apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
       app: app1
    spec:
      containers:
      - name: app1
        image: mahe1120/app1:1.0.0
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:631919637519:certificate/e0f16a97-e1a5-464d-b1b3-10e14c0dd064
    alb.ingress.kubernetes.io/group.name: mahe1120
spec:
  ingressClassName: alb
  rules:
  - host: "app1.mahedevops.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80


  


